In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('FILES\sales_data.csv')

In [3]:
df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [4]:
df.groupby(['Category','Sub-Category'])['Sales'].sum()

Category         Sub-Category
Furniture        Bookcases       114879.9963
                 Chairs          328449.1030
                 Furnishings      91705.1640
                 Tables          206965.5320
Office Supplies  Appliances      107532.1610
                 Art              27118.7920
                 Binders         203412.7330
                 Envelopes        16476.4020
                 Fasteners         3024.2800
                 Labels           12486.3120
                 Paper            78479.2060
                 Storage         223843.6080
                 Supplies         46673.5380
Technology       Accessories     167380.3180
                 Copiers         149528.0300
                 Machines        189238.6310
                 Phones          330007.0540
Name: Sales, dtype: float64

In [5]:
df.groupby(['Category','Sub-Category'])['Sales'].min()

Category         Sub-Category
Furniture        Bookcases        35.490
                 Chairs           26.640
                 Furnishings       1.892
                 Tables           24.368
Office Supplies  Appliances        0.444
                 Art               1.344
                 Binders           0.556
                 Envelopes         1.632
                 Fasteners         1.240
                 Labels            2.088
                 Paper             3.380
                 Storage           4.464
                 Supplies          1.744
Technology       Accessories       0.990
                 Copiers         299.990
                 Machines         11.560
                 Phones            2.970
Name: Sales, dtype: float64

In [6]:
df.groupby(['Category','Sub-Category'])['Sales'].max()

Category         Sub-Category
Furniture        Bookcases        4404.900
                 Chairs           4416.174
                 Furnishings      1336.440
                 Tables           4297.644
Office Supplies  Appliances       2625.120
                 Art              1113.024
                 Binders          9892.740
                 Envelopes         604.656
                 Fasteners          93.360
                 Labels            786.480
                 Paper             733.950
                 Storage          2934.330
                 Supplies         8187.650
Technology       Accessories      3347.370
                 Copiers         17499.950
                 Machines        22638.480
                 Phones           4548.810
Name: Sales, dtype: float64

In [7]:
df.groupby(['Segment','Category','Sub-Category'])['Sales'].agg(['min', 'max', 'sum'])

                                              min        max          sum
Segment     Category        Sub-Category
Consumer    Furniture       Bookcases      35.490   4228.704   68632.7290
                            Chairs         29.980   4416.174  172862.7420
                            Furnishings     1.988   1336.440   49620.0460
                            Tables         27.414   4297.644   99933.7950
            Office Supplies Appliances      0.444   2625.120   52819.5810
                            Art             1.344    303.840   14251.9300
                            Binders         0.852   9892.740  118161.0090
                            Envelopes       2.040    604.656    7771.1460
                            Fasteners       1.240     93.360    1680.9420
                            Labels          2.088    786.480    6709.2620
                            Paper           3.380    447.840   36324.3680
                            Storage         4.464   1801.632  100492.4020
                            Supplies        1.744   8187.650   25741.4960
            Technology      Accessories     1.584   3347.370   87105.2380
                            Copiers       299.990  13999.960   69819.0700
                            Machines       12.585   8749.950   79542.8250
                            Phones          5.560   4548.810  169932.7640
Corporate   Furniture       Bookcases      46.384   4404.900   34005.9243
                            Chairs         26.640   3504.900   99140.8780
                            Furnishings     1.892    756.800   25001.2660
                            Tables         24.368   3393.680   70871.7175
            Office Supplies Appliances      1.624   2518.290   36588.6830
                            Art             1.344   1113.024    8590.4480
                            Binders         0.556   5083.960   51560.3130
                            Envelopes       1.632    419.900    5942.6700
                            Fasteners       1.448     45.920     783.2900
                            Labels          2.520    629.184    4101.6460
                            Paper           3.424    733.950   23883.1300
                            Storage         8.384   2934.330   79790.9980
                            Supplies        6.280   4912.590   19435.2840
            Technology      Accessories     1.980   2249.910   48190.5640
                            Copiers       319.984  17499.950   46829.3860
                            Machines       59.994   9099.930   60276.7550
                            Phones          4.950   3499.930   91153.4140
Home Office Furniture       Bookcases      61.960   1497.666   12241.3430
                            Chairs         33.940   2676.672   56445.4830
                            Furnishings     2.032   1049.200   17083.8520
                            Tables         79.974   2348.820   36160.0195
            Office Supplies Appliances      7.780   1927.590   18123.8970
                            Art             1.408    289.200    4276.4140
                            Binders         1.408   4535.976   33691.4110
                            Envelopes       3.264    335.720    2762.5860
                            Fasteners       1.810     49.792     560.0480
                            Labels          2.464    100.240    1675.4040
                            Paper           3.808    629.100   18271.7080
                            Storage         4.768   2591.560   43560.2080
                            Supplies        3.488    357.930    1496.7580
            Technology      Accessories     0.990   2249.910   32084.5160
                            Copiers       479.984  11199.968   32879.5740
                            Machines       11.560  22638.480   49419.0510
                            Phones          2.970   4158.912   68920.8760